package contalletres;

import java.util.NoSuchElementException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import librerias.jerarquicos.ABC;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jesus
 */
public class MainForm extends javax.swing.JFrame {

    private static final int ASCIIEXTENDED = 255;
    private final ArrayList<InfoSilabas> silabas;
    private final ArrayList<String> palabras;
    private final int[] countLetras;
    private final int[] countIniciales;
    private Languages language;
    private GameType gameType;
    private ABC<String> bst;
    private final List<String> wordsNotInDic;

    /**
     * Creates new form mainform
     */
    public MainForm() {
        initComponents();
        configRadioButtons();
        language = Languages.SPANISH;
        langjLabel.setText(language.getLanguageName());
        gameType = GameType.WORDS;

        silabas = new ArrayList<>();
        palabras = new ArrayList<>();
        countLetras = new int[ASCIIEXTENDED];
        countIniciales = new int[ASCIIEXTENDED];
        wordsNotInDic = new ArrayList<>();

        letrasjTextArea.setLineWrap(true);
        inicialesjTextArea.setLineWrap(true);
        silabasjTextArea.setLineWrap(true);
        inputjTextArea.setLineWrap(true);
    }

    private void configRadioButtons() {
        esjRadioButtonMenuItem.setSelected(true);
        esjRadioButtonMenuItem.setActionCommand(Languages.SPANISH.getLanguageName());
        enjRadioButtonMenuItem.setActionCommand(Languages.ENGLISH.getLanguageName());
        valjRadioButtonMenuItem.setActionCommand(Languages.VALENCIAN.getLanguageName());
        esjRadioButtonMenuItem.setText(Languages.SPANISH.getLanguageName());
        enjRadioButtonMenuItem.setText(Languages.ENGLISH.getLanguageName());
        valjRadioButtonMenuItem.setText(Languages.VALENCIAN.getLanguageName());

        wordsjRadioButtonMenuItem.setText(GameType.WORDS.getGameTypeName());
        sentencesjRadioButtonMenuItem.setText(GameType.SENTENCES.getGameTypeName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorjDialog = new javax.swing.JDialog();
        langButtonGroup = new javax.swing.ButtonGroup();
        gameTypebuttonGroup = new javax.swing.ButtonGroup();
        procesarButton = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputjTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        silabasjTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        inicialesjTextArea = new javax.swing.JTextArea();
        letrasLabel = new java.awt.Label();
        inicialesLabel = new java.awt.Label();
        jScrollPane4 = new javax.swing.JScrollPane();
        letrasjTextArea = new javax.swing.JTextArea();
        silabasLabel = new java.awt.Label();
        label6 = new java.awt.Label();
        langjLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        filejMenu = new javax.swing.JMenu();
        savejMenuItem = new javax.swing.JMenuItem();
        printjMenuItem = new javax.swing.JMenuItem();
        languagejMenu = new javax.swing.JMenu();
        esjRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        enjRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        valjRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        gameTypejMenu = new javax.swing.JMenu();
        wordsjRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        sentencesjRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();

        errorjDialog.setTitle("Error Message");

        javax.swing.GroupLayout errorjDialogLayout = new javax.swing.GroupLayout(errorjDialog.getContentPane());
        errorjDialog.getContentPane().setLayout(errorjDialogLayout);
        errorjDialogLayout.setHorizontalGroup(
            errorjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        errorjDialogLayout.setVerticalGroup(
            errorjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contar lletres");
        setName("FormPpal"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        procesarButton.setActionCommand("Calcular");
        procesarButton.setLabel("Procesar");
        procesarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarButtonActionPerformed(evt);
            }
        });

        inputjTextArea.setColumns(20);
        inputjTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        inputjTextArea.setRows(5);
        jScrollPane1.setViewportView(inputjTextArea);

        silabasjTextArea.setEditable(false);
        silabasjTextArea.setColumns(20);
        silabasjTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        silabasjTextArea.setRows(5);
        silabasjTextArea.setTabSize(2);
        jScrollPane2.setViewportView(silabasjTextArea);

        inicialesjTextArea.setEditable(false);
        inicialesjTextArea.setColumns(20);
        inicialesjTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        inicialesjTextArea.setRows(5);
        inicialesjTextArea.setTabSize(2);
        jScrollPane3.setViewportView(inicialesjTextArea);

        letrasLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        letrasLabel.setText("LETRAS");

        inicialesLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inicialesLabel.setText("INICIALES");

        letrasjTextArea.setEditable(false);
        letrasjTextArea.setColumns(20);
        letrasjTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        letrasjTextArea.setRows(5);
        letrasjTextArea.setTabSize(2);
        jScrollPane4.setViewportView(letrasjTextArea);

        silabasLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        silabasLabel.setText(" SÍLABAS");

        label6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label6.setText("PALABRAS");

        langjLabel.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        langjLabel.setForeground(new java.awt.Color(0, 0, 204));
        langjLabel.setText("jLabel1");

        filejMenu.setText("File");
        filejMenu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        savejMenuItem.setText("Save");
        savejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(savejMenuItem);

        printjMenuItem.setText("Print");
        printjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printjMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(printjMenuItem);

        jMenuBar1.add(filejMenu);

        languagejMenu.setText("Language");
        languagejMenu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        langButtonGroup.add(esjRadioButtonMenuItem);
        esjRadioButtonMenuItem.setSelected(true);
        esjRadioButtonMenuItem.setName(""); // NOI18N
        esjRadioButtonMenuItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                langjRadioButtonMenuItemItemStateChanged(evt);
            }
        });
        languagejMenu.add(esjRadioButtonMenuItem);

        langButtonGroup.add(enjRadioButtonMenuItem);
        enjRadioButtonMenuItem.setName(""); // NOI18N
        enjRadioButtonMenuItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                langjRadioButtonMenuItemItemStateChanged(evt);
            }
        });
        languagejMenu.add(enjRadioButtonMenuItem);

        langButtonGroup.add(valjRadioButtonMenuItem);
        valjRadioButtonMenuItem.setName(""); // NOI18N
        valjRadioButtonMenuItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                langjRadioButtonMenuItemItemStateChanged(evt);
            }
        });
        languagejMenu.add(valjRadioButtonMenuItem);

        jMenuBar1.add(languagejMenu);

        gameTypejMenu.setText("Type");
        gameTypejMenu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        gameTypebuttonGroup.add(wordsjRadioButtonMenuItem);
        wordsjRadioButtonMenuItem.setSelected(true);
        wordsjRadioButtonMenuItem.setName(""); // NOI18N
        wordsjRadioButtonMenuItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                wordsjRadioButtonMenuItemItemStateChanged(evt);
            }
        });
        gameTypejMenu.add(wordsjRadioButtonMenuItem);

        gameTypebuttonGroup.add(sentencesjRadioButtonMenuItem);
        sentencesjRadioButtonMenuItem.setName(""); // NOI18N
        gameTypejMenu.add(sentencesjRadioButtonMenuItem);

        jMenuBar1.add(gameTypejMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(langjLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(procesarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(letrasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(inicialesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(silabasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(langjLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(letrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inicialesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silabasLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(procesarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(384, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuentaSilabas(String palabra) {
        SeparaSilabas s = new SeparaSilabas(palabra);
        String palabraDescompuesta = s.silabear();
        InfoSilabas infoSilabas;
        boolean found;
        for (String silaba : palabraDescompuesta.split("-")) {
            found = false;
            for (InfoSilabas is : silabas) {
                if (silaba.equals(is.getSilaba())) {
                    found = true;
                    is.incrementCount();
                    break;
                }
            }
            if (!found) {
                infoSilabas = new InfoSilabas(silaba);
                infoSilabas.incrementCount();
                silabas.add(infoSilabas);
            }
        }
    }

    private void countSyllables(String word) {
        Syllabifier s = new Syllabifier();
        List<String> syllables = s.getSyllables(word);
        String syllable = "";
        for (int i = 0; i < syllables.size(); ++i) {
            String letter = syllables.get(i);
            if (letter.equals("-") || letter.equals("/")
                    || letter.equals("+") || letter.equals("_")
                    || (i + 1) == syllables.size() - 1) {       //[e, /, x, a, m, -, p, l, e]
                if ((i + 1) == syllables.size() - 1) {          //[l, a, n, -, g, u, _, a, g, e]
                    syllable += letter + syllables.get(i + 1);  //[s, y, l, -, l, a, /, b, i, /, f, i, +, e, +, r]
                }
                InfoSilabas infoSilabas;
                boolean exists = false;
                for (InfoSilabas is : silabas) {
                    if (syllable.equals(is.getSilaba())) {
                        exists = true;
                        is.incrementCount();
                        break;
                    }
                }
                if (!exists) {
                    infoSilabas = new InfoSilabas(syllable);
                    infoSilabas.incrementCount();
                    silabas.add(infoSilabas);
                }
                syllable = "";
            } else {
                syllable += letter;
            }
        }
    }

    private void coutSyllablesDic(String word) {
        try {
            System.out.println("WORD " + word);
            String dicEntry = bst.getSubstring(word);
            String syllables = dicEntry.substring(dicEntry.indexOf("=") + 1);
            System.out.println("GET SUBSTRING " + syllables);

            boolean found;
            InfoSilabas infoSilabas;
            String separador = syllables.contains("·") ? "·" : " ";
            for (String syllable : syllables.split(separador)) {
                found = false;
                for (InfoSilabas is : silabas) {
                    if (syllable.equals(is.getSilaba())) {
                        found = true;
                        is.incrementCount();
                        break;
                    }
                }
                if (!found) {
                    infoSilabas = new InfoSilabas(syllable);
                    infoSilabas.incrementCount();
                    silabas.add(infoSilabas);
                }
            }
        } catch (NoSuchElementException nsee) {
            wordsNotInDic.add(word);
        }
    }

    private void procesarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarButtonActionPerformed
        cleanArrays();
        filterInputText();  //eliminar palabras repetidas y caracteres inválidos según language
        try {
            for (String word : palabras) {  //les paraules estan en lowerCase
                //STORE SYLLABLES IN ARRAYLIST silabas
                word = word.trim();         //Diana vol sílabes minúscules, inicials/lletres majúscules
                switch (language) {
                    case SPANISH:
                        cuentaSilabas(word);
                        break;
                    case ENGLISH:
                        coutSyllablesDic(word);
                        break;
                    case VALENCIAN:
                        cuentaSilabas(word);
                        break;
                    default:
                        break;
                }
                if (!wordsNotInDic.contains(word)) {
                    //STORE LETTERS & INITIALS
                    word = word.toUpperCase();
                    for (int i = 0; i < word.length(); ++i) {
                        char letter = word.charAt(i);
                        int ascii = (int) letter;
                        if (ascii <= ASCIIEXTENDED) {   //index out of bounds (not asciiExtended character)
                            if (i == 0) {
                                ++countIniciales[ascii];
                            }
                            ++countLetras[ascii];
                        }
                    }
                }
            }
            cleanTextAreas();
            formatPalabras("ui");
            formatLetras("ui");
            formatIniciales("ui");
            formatSilabas("ui");
            if (!wordsNotInDic.isEmpty()) {
                storeNewWords();
                String errorMsg = "Consulta el archivo newWords.txt";
                JOptionPane.showMessageDialog(null, errorMsg, "Missatge d'error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            String errorMsg = "Ha ocorregut un error inesperat\nPosat en contacte amb el teu germà per a solventar-ho";
            JOptionPane.showMessageDialog(null, errorMsg, "Missatge d'error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_procesarButtonActionPerformed

    private void storeNewWords() {
        PrintWriter pw;
        try {
            pw = new PrintWriter(new File("newWords.txt"));
            wordsNotInDic.forEach((st) -> {
                pw.println(st);
            });
            pw.close();
        } catch (FileNotFoundException fnfe) {
            System.err.println(fnfe.getMessage());
        }
    }

    /**
     * FUTURE IMPROVEMENT: -filter characters according to type of game (words,
     * sentences-punctuation)
     */
    private void filterInputText() {
        FilterStrings fs;
        String text = inputjTextArea.getText().toLowerCase();
        if (gameType.equals(GameType.WORDS)) {
            for (String word : text.split("\\s")) {
                fs = new FilterStrings(gameType, word, language);
                word = fs.filterLanguage();
                if (!word.equals("") && !palabras.contains(word)) {
                    palabras.add(word);
                }
            }
        } else if (gameType.equals(GameType.SENTENCES)) {  //hay que definir el separador entre frases
            fs = new FilterStrings(gameType, text, language);                   //no furula bien esto
            text = fs.filterLanguage();
        }
    }

    private void cleanArrays() {
        Arrays.fill(countIniciales, 0);
        Arrays.fill(countLetras, 0);
        silabas.clear();
        palabras.clear();
        wordsNotInDic.clear();
    }

    private String formatPalabras(String tipo) {
        String txt = "";
        for (String word : palabras) {
            txt += "\n" + word;
        }
        txt = txt.trim(); //remove "" to avoid showing in UI
        if (tipo.equals("ui")) {
            inputjTextArea.setText(txt);
        }
        return txt;
    }

    private String formatLetras(String tipo) {
        int sumaLetras = 0;
        String txt = "";
        String separador = "";
        if (tipo.equals("ui")) {
            separador = "\t";
        } else if (tipo.equals("file")) {
            separador = " ";
        }
        for (int i = 0; i < countLetras.length; ++i) {
            if (countLetras[i] > 0) {
                sumaLetras += countLetras[i];
                char letter = (char) i;
                txt += "\n" + letter + separador + "—" + separador + countLetras[i];
            }
        }
        txt = txt.trim();
        if (tipo.equals("ui")) {
            letrasLabel.setText(letrasLabel.getText() + " (" + sumaLetras + ") ");
            letrasjTextArea.setText(txt);
        }
        return txt;
    }

    private String formatIniciales(String tipo) {
        int sumaIniciales = 0;
        String txt = "";
        String separador = "";
        if (tipo.equals("ui")) {
            separador = "\t";
        } else if (tipo.equals("file")) {
            separador = " ";
        }
        for (int i = 0; i < countIniciales.length; ++i) {
            if (countIniciales[i] > 0) {
                sumaIniciales += countIniciales[i];
                char letter = (char) i;
                txt += "\n" + letter + separador + "—" + separador + countIniciales[i];
            }
        }
        txt = txt.trim();
        if (tipo.equals("ui")) {
            inicialesLabel.setText(inicialesLabel.getText() + " (" + sumaIniciales + ") ");
            inicialesjTextArea.setText(txt);
        }
        return txt;
    }

    private String formatSilabas(String tipo) {
        int sumaSilabas = 0;
        int numSilabas1Letras = 0, numSilabas2Letras = 0, numSilabas3Letras = 0;
        String txt = "";
        String separador = "";
        if (tipo.equals("ui")) {
            separador = "\t";
        } else if (tipo.equals("file")) {
            separador = " ";
        }
        for (InfoSilabas is : silabas) {
            if (is.getCount() > 0) {
                sumaSilabas += is.getCount();
                txt += "\n" + is.getSilaba() + separador + "—" + separador + is.getCount();
                switch (is.getSilLength()) {
                    case 1:
                        numSilabas1Letras += is.getCount();
                        break;
                    case 2:
                        numSilabas2Letras += is.getCount();
                        break;
                    case 3:
                        numSilabas3Letras += is.getCount();
                        break;
                }
            }
        }
        txt = txt.trim();
        if (tipo.equals("ui")) {
            silabasLabel.setText(silabasLabel.getText()
                    + "(" + sumaSilabas + ")"
                    + "=" + numSilabas1Letras
                    + "-" + numSilabas2Letras
                    + "-" + numSilabas3Letras);
            silabasjTextArea.setText(txt);
        }
        return txt;
    }

    private void cleanTextAreas() {
        inputjTextArea.setText("");
        silabasjTextArea.setText("");
        inicialesjTextArea.setText("");
        letrasjTextArea.setText("");
        silabasLabel.setText("SÍLABAS");
        inicialesLabel.setText("INICIALES");
        letrasLabel.setText("LETRAS");
    }

    private void savejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejMenuItemActionPerformed
        if (!verifyTextAreas()) {
            String errorMsg = "Introdueix dades abans de guardar\n";
            JOptionPane.showMessageDialog(null, errorMsg, "Missatge d'error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JFileChooser saveFile = new JFileChooser();
        saveFile.setSelectedFile(new File("paraules.txt"));
        saveFile.showSaveDialog(null);
        String path = saveFile.getSelectedFile().getAbsolutePath();
        saveToFile(path);
        JOptionPane.showMessageDialog(null, "Fitxer guardat correctament", "Informació", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_savejMenuItemActionPerformed

    private void printjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printjMenuItemActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new Print(this));
        /*boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
            } catch (PrinterException ex) {
            }
        }*/
    }//GEN-LAST:event_printjMenuItemActionPerformed

    private void langjRadioButtonMenuItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_langjRadioButtonMenuItemItemStateChanged
        String lang = langButtonGroup.getSelection().getActionCommand();
        if (lang.equals(Languages.SPANISH.getLanguageName())) {
            language = Languages.SPANISH;
        } else if (lang.equals(Languages.ENGLISH.getLanguageName())) {
            loadBST();
            showBST();
            language = Languages.ENGLISH;
        } else if (lang.equals(Languages.VALENCIAN.getLanguageName())) {
            language = Languages.VALENCIAN;
        }
        langjLabel.setText(language.getLanguageName());
    }//GEN-LAST:event_langjRadioButtonMenuItemItemStateChanged

    private void showBST() {    //sólo para inglés
        //System.out.println("inOrdre " + bst.inOrdre());
        System.out.println("El maxim " + bst.max());
        System.out.println("El minim " + bst.min());
        System.out.println("Talla " + bst.getSize());
//        System.out.println("Nombre de nodes " + bst.numNodes());
//        System.out.println("Nombre de fulles " + bst.numFulles());
//        System.out.println("Per nivells " + bst.perNivells());
//        System.out.println("A nivell 3 " + bst.contarANivell(3));
    }

    private void finalFile() {
        String[] vec = new String[45477];
        Scanner s, sr;
        PrintWriter pw;
        String entry, entryR, word, wordR;
        List<Integer> randNumList = new ArrayList<>();
        for (int i = 0; i < 45477; ++i) {
            randNumList.add(i);
        }
        Collections.shuffle(randNumList);
        int i = 0;
        try {
            s = new Scanner(new File("syllables.txt"));
            pw = new PrintWriter(new File("SYLLABLESfinal.txt"));
            while (s.hasNext()) {
                entry = s.nextLine();
                int pos = randNumList.get(i++);
                vec[pos] = entry;
            }
            s.close();
            for (String st : vec) {
                pw.println(st);
            }
            pw.close();
        } catch (FileNotFoundException fnfe) {
            System.err.println(fnfe.getMessage());
        }
    }

    private void loadBST() {
        Scanner s;
        bst = new ABC();
        String entry;
        try {
            s = new Scanner(new File("syllables.txt"));
            int i = 0;
            while (s.hasNext()) {
                entry = s.nextLine();
                bst.inserir(entry);
            }
            s.close();
        } catch (FileNotFoundException fnfe) {
            System.err.println(fnfe.getMessage());
        }
    }

    private void wordsjRadioButtonMenuItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_wordsjRadioButtonMenuItemItemStateChanged
        if (wordsjRadioButtonMenuItem.isSelected()) {
            gameType = GameType.WORDS;
        } else {
            gameType = GameType.SENTENCES;
        }
        System.out.println(gameType.getGameTypeName());
    }//GEN-LAST:event_wordsjRadioButtonMenuItemItemStateChanged

    private void saveToFile(String path) {
        try {
            PrintWriter pw = new PrintWriter(new File(path));
            writeToFile(pw, "CABECERA");
            writeToFile(pw, "PALABRAS");
            writeToFile(pw, "LETRAS");
            writeToFile(pw, "INICIALES");
            writeToFile(pw, "SÍLABAS");
            pw.close();
        } catch (FileNotFoundException e) {
            System.err.println("Error opening or creating " + path);
            JOptionPane.showMessageDialog(null, "No s'ha guardat", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void writeToFile(PrintWriter pw, String tipo) {
        if (tipo.equals("CABECERA")) {
            pw.println();
            pw.println("\t\t\tIDIOMA: " + language);
            pw.println("-------------------------------------------------------------------");
        } else {
            pw.println();
            pw.println("*************************");
            pw.println("\t" + tipo);
            pw.println("*************************");
            switch (tipo) {
                case "PALABRAS":
                    pw.print(formatPalabras("file"));
                    break;
                case "LETRAS":
                    pw.print(formatLetras("file"));
                    break;
                case "INICIALES":
                    pw.print(formatIniciales("file"));
                    break;
                case "SÍLABAS":
                    pw.print(formatSilabas("file"));
            }
            pw.println();
        }
    }

    private boolean verifyTextAreas() {
        return !(inputjTextArea.getText().equals("") && letrasjTextArea.getText().equals(""));
    }

    public String getLetras() {
        return letrasjTextArea.getText();
    }

    public String getIniciales() {
        return inicialesjTextArea.getText();
    }

    public String getSilabas() {
        return silabasjTextArea.getText();
    }

    public String getPalabras() {
        return inputjTextArea.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem enjRadioButtonMenuItem;
    private javax.swing.JDialog errorjDialog;
    private javax.swing.JRadioButtonMenuItem esjRadioButtonMenuItem;
    private javax.swing.JMenu filejMenu;
    private javax.swing.ButtonGroup gameTypebuttonGroup;
    private javax.swing.JMenu gameTypejMenu;
    private java.awt.Label inicialesLabel;
    private javax.swing.JTextArea inicialesjTextArea;
    private javax.swing.JTextArea inputjTextArea;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label6;
    private javax.swing.ButtonGroup langButtonGroup;
    private javax.swing.JLabel langjLabel;
    private javax.swing.JMenu languagejMenu;
    private java.awt.Label letrasLabel;
    private javax.swing.JTextArea letrasjTextArea;
    private javax.swing.JMenuItem printjMenuItem;
    private java.awt.Button procesarButton;
    private javax.swing.JMenuItem savejMenuItem;
    private javax.swing.JRadioButtonMenuItem sentencesjRadioButtonMenuItem;
    private java.awt.Label silabasLabel;
    private javax.swing.JTextArea silabasjTextArea;
    private javax.swing.JRadioButtonMenuItem valjRadioButtonMenuItem;
    private javax.swing.JRadioButtonMenuItem wordsjRadioButtonMenuItem;
    // End of variables declaration//GEN-END:variables
}
