package contalletres;

import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jesus
 */
public class MainForm extends javax.swing.JFrame {

    private static final int ASCIIEXTENDED = 255;
    private ArrayList<InfoSilabas> silabas;
    private ArrayList<String> palabras;
    private int[] countLetras;
    private int[] countIniciales;

    /**
     * Creates new form mainform
     */
    public MainForm() {
        initComponents();
        silabas = new ArrayList<>();
        palabras = new ArrayList<>();
        countLetras = new int[ASCIIEXTENDED];
        countIniciales = new int[ASCIIEXTENDED];
        letrasjTextArea.setLineWrap(true);
        inicialesjTextArea.setLineWrap(true);
        silabasjTextArea.setLineWrap(true);
        inputjTextArea.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorjDialog = new javax.swing.JDialog();
        procesarButton = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputjTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        silabasjTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        inicialesjTextArea = new javax.swing.JTextArea();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jScrollPane4 = new javax.swing.JScrollPane();
        letrasjTextArea = new javax.swing.JTextArea();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        filejMenu = new javax.swing.JMenu();
        savejMenuItem = new javax.swing.JMenuItem();
        printjMenuItem = new javax.swing.JMenuItem();

        errorjDialog.setTitle("Error Message");

        javax.swing.GroupLayout errorjDialogLayout = new javax.swing.GroupLayout(errorjDialog.getContentPane());
        errorjDialog.getContentPane().setLayout(errorjDialogLayout);
        errorjDialogLayout.setHorizontalGroup(
            errorjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        errorjDialogLayout.setVerticalGroup(
            errorjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contar lletres");
        setName("FormPpal"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        procesarButton.setActionCommand("Calcular");
        procesarButton.setLabel("Procesar");
        procesarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarButtonActionPerformed(evt);
            }
        });

        inputjTextArea.setColumns(20);
        inputjTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        inputjTextArea.setRows(5);
        jScrollPane1.setViewportView(inputjTextArea);

        silabasjTextArea.setEditable(false);
        silabasjTextArea.setColumns(20);
        silabasjTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        silabasjTextArea.setRows(5);
        silabasjTextArea.setTabSize(2);
        jScrollPane2.setViewportView(silabasjTextArea);

        inicialesjTextArea.setEditable(false);
        inicialesjTextArea.setColumns(20);
        inicialesjTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        inicialesjTextArea.setRows(5);
        inicialesjTextArea.setTabSize(2);
        jScrollPane3.setViewportView(inicialesjTextArea);

        label3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label3.setText("LETRAS");

        label4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label4.setText("INICIALES");

        letrasjTextArea.setEditable(false);
        letrasjTextArea.setColumns(20);
        letrasjTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        letrasjTextArea.setRows(5);
        letrasjTextArea.setTabSize(2);
        jScrollPane4.setViewportView(letrasjTextArea);

        label5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label5.setText(" SÍLABAS (castellano)");

        label6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label6.setText("PALABRAS");

        filejMenu.setText("File");
        filejMenu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        savejMenuItem.setText("Save");
        savejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(savejMenuItem);

        printjMenuItem.setText("Print");
        printjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printjMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(printjMenuItem);

        jMenuBar1.add(filejMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(procesarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(procesarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuentaSilabas(String palabra) {
        SeparaSilabas s = new SeparaSilabas(palabra);
        String palabraDescompuesta = s.silabear();
        InfoSilabas infoSilabas;
        boolean found;
        for (String silaba : palabraDescompuesta.split("-")) {
            found = false;
            for (InfoSilabas is : silabas) {
                if (silaba.equals(is.getSilaba())) {
                    found = true;
                    is.incrementCount();
                    break;
                }
            }
            if (!found) {
                infoSilabas = new InfoSilabas(silaba);
                infoSilabas.incrementCount();
                silabas.add(infoSilabas);
            }
        }
    }

    private void countSyllables(String word) {
        Syllabifier s = new Syllabifier();
        List<String> syllables = s.getSyllables(word);
        System.out.println(syllables);
        String syllable = "";
        for (int i = 0; i < syllables.size(); ++i) {
            String letter = syllables.get(i);
            System.out.println(letter);
            if (letter.equals("-") || letter.equals("/")
                    || letter.equals("+") || letter.equals("_")
                    || (i + 1) == syllables.size() - 1) {       //[e, /, x, a, m, -, p, l, e]
                if ((i + 1) == syllables.size() - 1) {          //[l, a, n, -, g, u, _, a, g, e]
                    syllable += letter + syllables.get(i + 1);  //[s, y, l, -, l, a, /, b, i, /, f, i, +, e, +, r]
                }
                InfoSilabas infoSilabas;
                boolean exists = false;
                for (InfoSilabas is : silabas) {
                    if (syllable.equals(is.getSilaba())) {
                        exists = true;
                        is.incrementCount();
                        break;
                    }
                }
                if (!exists) {
                    infoSilabas = new InfoSilabas(syllable);
                    infoSilabas.incrementCount();
                    silabas.add(infoSilabas);
                }
                syllable = "";
            } else {
                syllable += letter;
            }
        }
    }
 
    private void procesarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarButtonActionPerformed
        // TODO add your handling code here:
        cleanArrays();
        filterInputText();
        try {
            for (String word : palabras) {  //les paraules estan en lowerCase
                word = word.trim();         //Diana vol sílabes minúscules, inicials/lletres majúscules
                //cuentaSilabas(word);
                countSyllables(word);
                word = word.toUpperCase();
                for (int i = 0; i < word.length(); ++i) {
                    char letter = word.charAt(i);
                    int ascii = (int) letter;
                    if (ascii <= ASCIIEXTENDED) {   //index out of bounds (not asciiExtended character)
                        if (i == 0) {
                            ++countIniciales[ascii];
                        }
                        ++countLetras[ascii];
                    }
                }
            }
            cleanTextAreas();
            formatPalabras("ui");
            formatLetras("ui");
            formatIniciales("ui");
            formatSilabas("ui");
        } catch (Exception e) {
            String errorMsg = "Ha ocorregut un error inesperat\nPosat en contacte amb el teu germà per a solventar-ho";
            JOptionPane.showMessageDialog(null, errorMsg, "Missatge d'error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_procesarButtonActionPerformed

    /**
     * FUTURE IMPROVEMENT: -filter characters according to language chosen in
     * menuBar (Spanish by now) -and according to type of game (words,
     * sentences-punctuation)
     */
    private void filterInputText() {
        String text = inputjTextArea.getText().toLowerCase();
        for (String word : text.split("\\s")) {
            FilterStrings fs = new FilterStrings("word", word);
            word = fs.filterSpanish();
            if (!palabras.contains(word)) {
                palabras.add(word);
            }
        }
    }

    private void cleanArrays() {
        Arrays.fill(countIniciales, 0);
        Arrays.fill(countLetras, 0);
        silabas.clear();
        palabras.clear();
    }

    private String formatPalabras(String tipo) {
        String txt = "";
        for (String word : palabras) {
            txt += "\n" + word;
        }
        txt = txt.trim(); //remove "" to avoid showing in UI
        if (tipo.equals("ui")) {
            inputjTextArea.setText(txt);
        }
        return txt;
    }

    private String formatLetras(String tipo) {
        String txt = "";
        String separador = "";
        if (tipo.equals("ui")) {
            separador = "\t";
        } else if (tipo.equals("file")) {
            separador = " ";
        }
        for (int i = 0; i < countLetras.length; ++i) {
            if (countLetras[i] > 0) {
                char letter = (char) i;
                txt += "\n" + letter + separador + "—" + separador + countLetras[i];
            }
        }
        txt = txt.trim();
        if (tipo.equals("ui")) {
            letrasjTextArea.setText(txt);
        }
        return txt;
    }

    private String formatIniciales(String tipo) {
        String txt = "";
        String separador = "";
        if (tipo.equals("ui")) {
            separador = "\t";
        } else if (tipo.equals("file")) {
            separador = " ";
        }
        for (int i = 0; i < countIniciales.length; ++i) {
            if (countIniciales[i] > 0) {
                char letter = (char) i;
                txt += "\n" + letter + separador + "—" + separador + countIniciales[i];
            }
        }
        txt = txt.trim();
        if (tipo.equals("ui")) {
            inicialesjTextArea.setText(txt);
        }
        return txt;
    }

    private String formatSilabas(String tipo) {
        String txt = "";
        String separador = "";
        if (tipo.equals("ui")) {
            separador = "\t";
        } else if (tipo.equals("file")) {
            separador = " ";
        }
        for (InfoSilabas is : silabas) {
            if (is.getCount() > 0) {
                txt += "\n" + is.getSilaba() + separador + "—" + separador + is.getCount();
            }
        }
        txt = txt.trim();
        if (tipo.equals("ui")) {
            silabasjTextArea.setText(txt);
        }
        return txt;
    }

    private void cleanTextAreas() {
        inputjTextArea.setText("");
        silabasjTextArea.setText("");
        inicialesjTextArea.setText("");
        letrasjTextArea.setText("");
    }

    private void savejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejMenuItemActionPerformed
        // TODO add your handling code here:
        if (!verifyTextAreas()) {
            String errorMsg = "Introdueix dades abans de guardar\n";
            JOptionPane.showMessageDialog(null, errorMsg, "Missatge d'error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JFileChooser saveFile = new JFileChooser();
        saveFile.setSelectedFile(new File("paraules.txt"));
        saveFile.showSaveDialog(null);
        String path = saveFile.getSelectedFile().getAbsolutePath();
        saveToFile(path);
        JOptionPane.showMessageDialog(null, "Fitxer guardat correctament", "Informació", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_savejMenuItemActionPerformed

    private void printjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printjMenuItemActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new Print(this));
        /*boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
            } catch (PrinterException ex) {
            }
        }*/
    }//GEN-LAST:event_printjMenuItemActionPerformed

    private void saveToFile(String path) {
        try {
            PrintWriter pw = new PrintWriter(new File(path));
            writeToFile(pw, "PALABRAS");
            writeToFile(pw, "LETRAS");
            writeToFile(pw, "INICIALES");
            writeToFile(pw, "SÍLABAS");
            pw.close();
        } catch (FileNotFoundException e) {
            System.err.println("Error opening or creating " + path);
            JOptionPane.showMessageDialog(null, "No s'ha guardat", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void writeToFile(PrintWriter pw, String tipo) {
        pw.println();
        pw.println("*************************");
        pw.println("\t" + tipo);
        pw.println("*************************");
        switch (tipo) {
            case "PALABRAS":
                pw.print(formatPalabras("file"));
                break;
            case "LETRAS":
                pw.print(formatLetras("file"));
                break;
            case "INICIALES":
                pw.print(formatIniciales("file"));
                break;
            case "SÍLABAS":
                pw.print(formatSilabas("file"));
        }
        pw.println();
    }

    private boolean verifyTextAreas() {
        return !(inputjTextArea.getText().equals("") && letrasjTextArea.getText().equals(""));
    }

    public String getLetras() {
        return letrasjTextArea.getText();
    }

    public String getIniciales() {
        return inicialesjTextArea.getText();
    }

    public String getSilabas() {
        return silabasjTextArea.getText();
    }

    public String getPalabras() {
        return inputjTextArea.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog errorjDialog;
    private javax.swing.JMenu filejMenu;
    private javax.swing.JTextArea inicialesjTextArea;
    private javax.swing.JTextArea inputjTextArea;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JTextArea letrasjTextArea;
    private javax.swing.JMenuItem printjMenuItem;
    private java.awt.Button procesarButton;
    private javax.swing.JMenuItem savejMenuItem;
    private javax.swing.JTextArea silabasjTextArea;
    // End of variables declaration//GEN-END:variables
}
